name: kow_form
description: Create easy serializable forms with KowForm by inserting KowInputs beneath KowForm in the widget tree. Use KowSubmitButton to submit your form's data.
version: 0.0.1
repository: https://github.com/kaionesyan/kow_form

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  provider: ^4.3.3